### ISSUE TITLE
Modify Package Publisher doesn't work due to wrong executable path

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/MSIX-Toolkit#12]
The modify-package-publisher.ps1 script requires to copy, inside the same folder, the signtool and packageeditor executables from the Windows 10 SDK. However, even after doing that, the script doesn't run properly since the executables are referenced in the following way:

```
#relative paths to the tools used to repackage and sign
$packageEditorExe = "PackageEditor.exe"
$signToolExe = "signtool.exe"
```

The script fails with the following error:

```
Suggestion [3,General]: The command signtool.exe was not found, but does exist in the current location. Winows PowerShell does not load commands from the current location by default. If you trust this command, instad type: ".\signtool.exe". See "get-help about_Command_Precedence" for more details.
```

Once I change the relative paths to include .\ as prefix, the script starts to work.

```
#relative paths to the tools used to repackage and sign
$packageEditorExe = ".\PackageEditor.exe"
$signToolExe = ".\signtool.exe"
```

Is it a real issue of the script or am I using it in the wrong way?

**Comment by c-don** [comment]
@qmatteoq - you are correct. I initially had the full path to a local folder where the tools were available. Can you do a PR that the team can review and approve. Thanks.

**Comment by qmatteoq** [comment]
Done with #13
