### ISSUE TITLE
AppInstallerFileBuilder ModificationPackages Section in appinstaller file not work

### ISSUE THREAD

**Issue by fankhpe** [microsoft/MSIX-Toolkit#16]
error 0xC00CE014: App manifest validation error: The app manifest must be valid as per schema: Line 11, Column 4, Reason: Element '{http://schemas.microsoft.com/appx/appinstaller/2017}ModificationPackages' is unexpected according to content model of parent element '{http://schemas.microsoft.com/appx/appinstaller/2017}

**Comment by jvintzel** [comment]
Looks like the app referenced a schema that was not implemented.  Modification Packages should be under the OptionalPackages element in the XML.

**Comment by Huios** [comment]
This is fixed in the new version of the AppInstaller File Builder

https://github.com/microsoft/MSIX-Toolkit/releases/download/1.3.3/AppInstallerFileBuilder_1.2019.1001.0.msix
