### ISSUE TITLE
Wrong labels in the auto-update configuration section

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/MSIX-Toolkit#8]
The auto-update configuration feature asks you first to select which Windows version you want to target. Based on the version, it proposes you different options, since not all of them are supported in every Windows 10 version.
However, I think the current labels aren't correct. Choosing Windows 10 1809 will enable features like Show Prompt or Blocking Update, which have been introduced in Windows 10 1903.

**Comment by jvintzel** [comment]
@Chaitanya <mailto:cdon@microsoft.com>

While the schema was there in 1809 it did not work for centennial. We should make it 1903.

John

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by c-don** [comment]
fixed - get new package [here](https://github.com/microsoft/MSIX-Toolkit/releases/download/v1.1/AppInstallerFileBuilder_1.2019.524.0_x86.appx)
